# API initialisation
api_name: "Your API Name"
protocol_type: "HTTP"
# deployment_stagename: "test" # errors out

# API Integration
integration_type: AWS_PROXY
integration_uri: arn:aws:lambda:ap-southeast-2:580440732180:function:GetStartedLambdaProxyIntegration
payload_version: "2.0"

# Stage
stage_name: "test" 

# Route  
route_key: "ANY /path"