---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: Your API Name
      ProtocolType: HTTP
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId:
        Ref: Api
  Integration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: Api
      IntegrationType: AWS_PROXY
      IntegrationUri: arn:aws:lambda:ap-southeast-2:580440732180:function:GetStartedLambdaProxyIntegration
      PayloadFormatVersion: '2.0'
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: Api
      StageName: test
  Route:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: Api
      RouteKey: ANY /path
Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    NoEcho: false
  EnvironmentType:
    Type: String
    Default: development
    NoEcho: false
    AllowedValues:
    - development
    - production
Description: apigatewayv2 - latest
Outputs:
  CfTemplateUrl:
    Value: https://580440732180.ap-southeast-2.cfhighlander.templates.s3.amazonaws.com/published-templates/apigatewayv2/latest/apigatewayv2.compiled.yaml
  CfTemplateVersion:
    Value: latest
